# Generated by Django 4.1.7 on 2023-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
