# Generated by Django 4.1.7 on 2023-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_booking_room_alter_hostel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostel')),
            ],
            options={
                'verbose_name': 'Room_category',
                'verbose_name_plural': 'Room_categories',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.roomcategory'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
