# Generated by Django 4.1.7 on 2023-03-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
    ]
