# Generated by Django 4.1.7 on 2023-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_hostel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
    ]
