# Generated by Django 4.1.7 on 2023-03-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hostel_app", "0004_alter_hostel_cover_alter_userprofile_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hostel",
            options={
                "ordering": ["name"],
                "verbose_name": "Hostel",
                "verbose_name_plural": "Hostels",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "UserLocation",
                "verbose_name_plural": "UserLocations",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                ("capacity", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_app.hostel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["room_number"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_email", models.EmailField(max_length=254)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_app.room",
                    ),
                ),
            ],
        ),
    ]
