# Generated by Django 4.1.7 on 2023-03-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_alter_hostel_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Booking',
        ),
    ]
